### ISSUE TITLE
[NPC] Sartharion [Buff] Gift of Twilight

### ISSUE THREAD

**Issue by AgentMalice** [Stormforge-gg/Bugtracker-Fordring#1423] opened 2022-06-19 20:30 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
In the Obsidian Sanctum Raid, Sartharion gains the Gift of Twilight buff at 80% and keeps it until all drakes are killed, allowing the raid to finish.
**Current behaviour**:
Gift of Twilight is keeping him immune to all damage for the rest of the fight, even after all drakes have been killed, until players die and reset.
**Expected behaviour**: 
It should fall off when the last Drake dies.
**Revision**:

**Comment by Cold-Martijn** [comment] 2022-06-19 20:32
hearsay: only happens when attempting OS 2D.

**Comment by Pawlld** [comment] 2022-06-19 20:34
**Description**: https://www.wowhead.com/spell=57835/gift-of-twilight is not removed on Shadron's death, which makes Sartharion unkillable

**Current behaviour**: Gift of twilight persist after Shadron's death

**Expected behaviour**: Gift of twilight should be removed from Sartharion after Shadron's death

**Comment by AgentMalice** [comment] 2022-06-19 20:37
it was 25m OS 2D (https://www.twitch.tv/videos/1508446474)

**Comment by Wolffenstein** [comment] 2022-06-19 21:51
Killing Shadron should NOT remove Gift of Twilight from Sartharion, you have to kill the Acolyte even if Shadron dies. The only issue here is the portal disappearing and that's due to a bug with Tenebron which will be fixed in revision 1532.

**Closed by Wolffenstein** 2022-06-19 21:51 UTC

**Comment by Pawlld** [comment] 2022-06-20 05:00
made some research. Yeah u're correct, but unfortunately that portal disappears.
