### ISSUE TITLE
Tirion's Gamble

### ISSUE THREAD

**Issue by Nyankat1** [Stormforge-gg/Bugtracker-Fordring#1320] opened 2022-06-13 14:54 UTC
Quest in Icecrown, TIrion's Gamble

NPC Tirion doesnt spawn, and cannot progress the quest. Acquired the quest item to disguise as a cultist, but no NPC to progress quest.

NPC doesnt spawn.

NPC spawns, progresses questline, completes quest.

Please fix the npc Tirion Fordring to actually show up and start the quest. He doesnt even spawn once server restarts.

**Comment by Cold-Martijn** [comment] 2022-07-11 13:13
duplicate of https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1219
(don't worry, fix incoming soon)

**Closed by Cold-Martijn** 2022-07-11 13:13 UTC
