### ISSUE TITLE
priest spirit of redeption bugged

### ISSUE THREAD

**Issue by Weuyn** [Stormforge-gg/Bugtracker-Fordring#1257] opened 2022-06-11 14:46 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
holy priests angel form that they turn into when they die can he targeted, attacked and killed, and also healed
**Current behaviour**:
as above
**Expected behaviour**: 
it should be untargetable, unattackable and immune to all spell effects, per description of the ability
**Revision**:

**Comment by Wolffenstein** [comment] 2022-06-11 14:48
cant reproduce

**Comment by Weuyn** [comment] 2022-06-11 15:01
Might not be able to get NPCs to kill you, but warriors were def duing it in wintergrasp to me yesterday. They would tap me when I go spirit of redemption and I wouldn't be able to cast anything. Would say 'you are dead' but wouldn't knock me out of the angel

**Comment by Weuyn** [comment] 2022-06-12 10:08
https://imgur.com/a/DwoS2P2 Did this in the last wintergrasp today @Wolffenstein

**Comment by Wolffenstein** [comment] 2022-06-12 16:19
Could you also screencap the combat log whenever this bug occurs?

**Comment by Wolffenstein** [comment] 2022-06-12 17:52
Hopefully fixed in rev 1511.

**Closed by Wolffenstein** 2022-06-12 17:52 UTC

**Comment by Weuyn** [comment] 2022-06-12 20:12
https://imgur.com/a/xWRj9j4 soulstone popped like this put me back in angel form lol. Thanks wolf, hope ites fixed too ^^ Was nothing in my clog, seems to be broken most of the time
