### ISSUE TITLE
[Quest][NPC][Icecrown] Tirion's Gambit

### ISSUE THREAD

**Issue by Exorcista** [Stormforge-gg/Bugtracker-Fordring#1601] opened 2022-07-08 01:59 UTC
**Description**:  Doing quest: https://www.wowhead.com/quest=13364/tirions-gambit, Tirion takes like 45min to respawn after someone does this quest

**Expected behaviour**:  Shorter respawn

**Revision**:  1593

**Comment by Cold-Martijn** [comment] 2022-07-11 13:13
duplicate of https://github.com/Stormforge-gg/Bugtracker-Fordring/issues/1219
(don't worry, fix incoming soon)

**Closed by Cold-Martijn** 2022-07-11 13:13 UTC
