### ISSUE TITLE
Deserter after leaving Random HC I joined that was 3/5 bosses dead already.

### ISSUE THREAD

**Issue by Secare69** [Stormforge-gg/Bugtracker-Fordring#1341] opened 2022-06-14 14:09 UTC
**Description**:  Queue'd up for random HC dungeon as tank, instant queue and hit accept. Teleported into the instance, Gundrak HC, and had a pop up saying instance already in progress or something, 3/5 bosses dead, would I like to accept the lockout and continue in the run. I hit no and got teleported out, not back to my previous location but to right outside the instance, so left the group and got a 30 min deserter debuff.

**Current behaviour**: As above

**Expected behaviour**:  Not sure if I should avoid the deserter debuff? Seems harsh to get 30 min deserter for not wanting to join a random HC 60% of the way through.

**Revision**:

**Comment by NatsumeLily** [comment] 2022-06-14 15:27
This is not a bug. 

Not sure about being teleported outside the instance when you declined. Think that should be where you were when you teleported in.

**Comment by Wolffenstein** [comment] 2022-06-14 16:30
Not a bug. Teleport fixed in rev 1519.

**Closed by Wolffenstein** 2022-06-14 16:30 UTC
