### ISSUE TITLE
[Quest] The Admiral Revealed [NPC] Grand Admiral Westwind

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Fordring#222] opened 2022-04-13 23:56 UTC
**Description**: 
https://www.wowhead.com/quest=12852/the-admiral-revealed
https://wowwiki-archive.fandom.com/wiki/Quest:The_Admiral_Revealed
Quest not working properlly, NPC completely missing.
**Current behaviour**:
NPC Grand Admiral Westwind is missing from the spot where he should be in the cave. 
![WoWScrnShot_041422_011521](https://user-images.githubusercontent.com/103254348/163286786-3912a5e8-dd86-40d3-a223-457faa0a9f29.jpg)
After 4 mob pack respawns that are near the place where he should be.
![WoWScrnShot_041422_011642](https://user-images.githubusercontent.com/103254348/163287004-10e479de-8457-4277-8155-d9a33d919e7d.jpg)
![WoWScrnShot_041422_012224](https://user-images.githubusercontent.com/103254348/163286935-b61b6e3c-092e-4c29-b191-27bbfe1264a5.jpg)
![WoWScrnShot_041422_013201](https://user-images.githubusercontent.com/103254348/163287071-cac2ef03-2565-4400-9361-201b274e981f.jpg)
Half an hour later re checking, still no NPC
![WoWScrnShot_041422_015318](https://user-images.githubusercontent.com/103254348/163288134-4a6c7388-43db-4e0c-9272-cbbdd6bda762.jpg)

**Expected behaviour**: 
https://wotlk.evowow.com/?npc=29621
https://www.wowhead.com/npc=29621/grand-admiral-westwind
![image](https://user-images.githubusercontent.com/103254348/163287226-2f003d0f-3f22-446a-815b-214b638a1446.png)
![image](https://user-images.githubusercontent.com/103254348/163287250-c0708e5a-e3b0-4339-9427-27930a0be69b.png)

Once quest Second Chances is complete you get a following quest The Admiral Revealed where you have to you use Lord Commander's Nullifier (https://wowwiki-archive.fandom.com/wiki/Lord-Commander%27s_Nullifier) on Grand Admiral Westwind.
Once he is at 50% or bellow you use the quest item, then he reveals his true identity and transforms into [Mal'Ganis](https://wowwiki-archive.fandom.com/wiki/Mal%27Ganis) and at 1% he opens a portal and escapes which completes the quest.
https://www.youtube.com/watch?v=9FZU1sGvLAU
https://www.youtube.com/watch?v=f9GcOoRbu9k

**Revision**:

**Comment by Evolvee** [comment] 2022-04-29 17:29
I cant reproduce this, can someone confirm?

**Comment by therealCrysis** [comment] 2022-05-14 16:05
Works correctly in rev 1179. :)

**Comment by Nuy** [comment] 2022-06-07 23:17
> I cant reproduce this, can someone confirm?

It's bugged right now. The problem is he's not respawning after someone did the quest so if you want to do it and he's not there then you need to wait for server restart for him to spawn.

**Comment by Evolvee** [comment] 2022-06-11 10:25
should be fixed in next rev

**Closed by Evolvee** 2022-06-11 10:25 UTC
