### ISSUE TITLE
[Dungeon][NPC] Utgrade Pinnacle

### ISSUE THREAD

**Issue by Amun12** [Stormforge-gg/Bugtracker-Fordring#1063] opened 2022-06-06 22:44 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**:   UP heroic seems to be severely undertuned compared to other heroic dungeons. While the damage seems okay, HP definitely needs buffing for both trash and bosses. Most of the trash have HP around 63k. Svala for example has only around 330k HP compared to some other dungeons where bosses' hp ranges from 800k to 1 million.

**Current behaviour**:

**Expected behaviour**: 

**Revision**:

**Comment by Godmatik** [comment] 2022-06-07 15:26
Confirmed - looks like the health buff for heroics was not applied to Utgarde Pinnacle.

**Comment by Wolffenstein** [comment] 2022-06-07 17:01
Fixed in rev 1449.

**Closed by Wolffenstein** 2022-06-07 17:01 UTC
